### ISSUE TITLE
Changes in the EG: line numebring

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#11]
Dear @erc-dharma/nusantara-epigraphy, 

Daniel has updated the line numbering schema in the EG, see p. 21 for more details. Considering you are working on copper-plates, you have the possibility to keep the numbering as you have already done it. But could you please check the following files to be sure it is still desirable and conformant to the EG? 

If you need help figuring a new numbering pattern for any file, ask @arlogriffiths and me. 

@aditiagunawan: 
- kebantenan_1
- kebantenan_2

@m-schoettel: 
- Canggu
- Paguhan
- Tirah 

@ekobastiawan : 
- Gandhakuti
- Mula-Malurung
- Ramesvarapura
- Terep_I
- Terep_II
- Kakuruyan
- Kusambya
- simaanglyang

Best,

**Comment by arlogriffiths** [comment]
Dear @m-schoettel, @aditiagunawan and @ekobastiawan : could you please make the necessary changes? You can follow the model for line-numbering in my file Marsmu.xml (after doing a git pull).

**Comment by arlogriffiths** [comment]
Dear @m-schoettel, @aditiagunawan and @ekobastiawan : please confirm that you've taken the necessary steps.

**Comment by ekobastiawan** [comment]
the line numbering has been updated Mas

**Comment by arlogriffiths** [comment]
Thanks @ekobastiawan .

@m-schoettel and @aditiagunawan : please take the necessary steps and reply to this message when you're done.

**Comment by m-schoettel** [comment]
Line numbering has been updated in all files encoding copper plates (including kabhagavanan and tuhanyaru).

**Comment by arlogriffiths** [comment]
@aditiagunawan : you're the last in line on this issue. Please let us know when you are done.

**Comment by arlogriffiths** [comment]
@aditiagunawan : we're still waiting for you...

**Comment by aditiagunawan** [comment]
@arlogriffiths sorry, it is done.
