### ISSUE TITLE
Change in the EG: new @loc reference system

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#12]
Dear @erc-dharma/nusantara-epigraphy, 

Among the changes made in March 2020 in the EG, the prefixes “p” and “m” are no longer necessary (and no longer permitted) in `@loc`; see EG p. 97 for more information. 
I was able to identify the use of the previous system in several of your files. Could you checked them and update the encoding when necessary? 

I don't dare to intervene myself since this change is related to line numbering. And I don't want to break the current links between the edition and the apparatus, making the update work more complicated for all of you. But let me know if you need help applying all the changes.

@aditiagunawan:
- kebantenan_1
- kebantenan_2  

@arlogriffiths : 
- Marsmu

@ekobastiawan :
- Gandhakuti
- Maribong
- Mula-Malurung
- PakisWetan
- Terep_I
- Terep_II
- Kakurugan

@m-schoettel : 
- Kabhagavanan
- Paguhan
- tuhanyaru

**Comment by arlogriffiths** [comment]
Dear @m-schoettel, @aditiagunawan and @ekobastiawan : could you please make the necessary changes? You can follow the model for line-numbering in my file Marsmu.xml (after doing a git pull).

**Comment by arlogriffiths** [comment]
Dear @ajaniak : could you please check my revised file Marsmu.xml? (As I showed you in a separate email, there is a validation problem on my side, but I don't think it is due to an encoding error.)

**Comment by m-schoettel** [comment]
Changes have been done and pushed.

**Comment by aditiagunawan** [comment]
It's done.

**Comment by arlogriffiths** [comment]
@ekobastiawan : let us know when you're done with this issue. After that, @ajaniak can let us know whether all our files are now compliant.

**Comment by ekobastiawan** [comment]
This was updated as well yesterday

**Comment by arlogriffiths** [comment]
Thanks Eko.

@ajaniak : please do another check for conformity of all tfc-nusantara-epigraphy files, and close this if you find no recalcitrant cases.

**Comment by ajaniak** [comment]
Dear @ekobastiawan, 

One have been forgotten in Gandhakuti
```
 <app loc="p1r-pr2">
                      <lem>Ahibuddhādevata</lem>
                      <rdg source="bib:Boechari1985-1986_01 bib:NinnySusanti2003_01">Ahibududdhādevāta</rdg>
                      </app>
```
I have changed it as `1r1-1r2`.
