### ISSUE TITLE
introduce <handDesc> into teiHeaders

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#13]
Dear @ajaniak : is it possible for you to modify all our already encoded files to insert the lines of code necessary for encoding `<handDesc>`, as we have them in template v2?

Dear @aditiagunawan, @ekobastiawan, @m-schoettel : see new version of EG 11.2 for instructions re. `<handDesc>`.

**Comment by ajaniak** [comment]
It has been done. Please check for files, and don't forget the git pull first!
