### ISSUE TITLE
Validation issue on Canggu

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#14]
Dear @m-schoettel,

Your first `<p>` tag element isn't closed. I think, it should be done at the end of the XML line 83 after 
```
<lb n="1r3" break="no"/>śa, nāgakaraṇa, karkkaṭarāśī,
```
Can you check this please? 

Best,

**Comment by m-schoettel** [comment]
Thanks for spotting this validation issue. I was just working on Canggu and made the necessary change. Will push the file at the end of the work session.

**Comment by arlogriffiths** [comment]
@m-schoettel : good. In the future, when you have done the necessary for an issue, feel free to close it yourself. I am doing do now.
