### ISSUE TITLE
About using <expan>

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#16]
Dear @arlogriffiths and @m-schoettel, 

You have been using `<expan>` in Canggu.xml and MpuMano.xml. Following the EG, it should only the `<abbr>`tag, see EG, p. 82. If you want the possibility to do it, EG needs to be changed. 
So that when DHARMA schema is released your files will validate and that such an encoding can be transformed later on. 

Best,

**Comment by arlogriffiths** [comment]
I have stripped the tagging down to `<abbr>` in MpuMano.xml. Thanks!

**Comment by m-schoettel** [comment]
Thanks Axelle! I have done the same in the Canggu file. I am closing this comment now.
