### ISSUE TITLE
About Wurare

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#17]
Dear @arlogriffiths, 

In Wuare.xml, you are using `<l n="3" enjamb="yes">` several times in the file, is it normal? When the `<l>`don't have @enjamb, you have been using `<l n="c">`. 

Best,

**Comment by arlogriffiths** [comment]
No, that is not normal. It was the result of an imperfect search and replace operation. Solved now. Thanks!
