### ISSUE TITLE
About <gap reason="lost" extent="unknown"/>

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#18]
Dear @arlogriffiths and @aditiagunawan, 

You have been using `<gap reason="lost" extent="unknown"/>` in Marmu.xml and Huladayeuh.xml, the `@unit` is still expected in this case. Could you please add it? 

Best,

**Comment by arlogriffiths** [comment]
Done for Marsmu.xml.

Aditia: you can make the changes in Huludayeuh.xml and use "resolves #18" as commit message; it will close this issue automatically.
