### ISSUE TITLE
About bibliographical references

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#19]
Dear @erc-dharma/nusantara-epigraphy, 

It seems you haven't really started working on those, but for some of you more advanced in their work, please take the following remarks into account: 
- the prefix `bib:` have been forgotten several times for both `@source` and `@target`, also it is necessary for the second reference, e.g not `bib:Bosch1928_01 Sarkar1971-1972_01` but `bib:Bosch1928_01 bib:Sarkar1971-1972_01`
- some shortTitles are not well formed (2 authors without the `+`, missing ending number.... ). Be careful with this, any mistake will make impossible retrieving data from Zotero.
- `@unit="annex` haven't been planed by the EG, could `@unit="appendix"` be enough ? 
- `<citedRange>` always take the attribute `@unit`. 

Best,

**Comment by arlogriffiths** [comment]
Thanks a lot.

- I am the source for the erroneous `bib:Bosch1928_01 Sarkar1971-1972_01`, and have now corrected that mistake in the relevant file.
- please indicate which files are concerned by the problem of ill-formed shortTitles
- yes, `@unit="appendix"` is fine: which files are concerned?
- which files lack @unit on `<citedRange>`

**Comment by ajaniak** [comment]
For @unit:
-  @aditiagunawan 
   - Batutulis
   - Huludayeuh
   - kawali_1a
   - kebantenan_1
   - kebantenan_2
   - Linggawangi.xml

- @arlogriffiths 
  - Wurare

- @ekobastiawan 
  - Gadhakuti
  - Maribong
  - PakisWetan

- @m-schoettel 
  - Canggu
  - Kusmala
  - Paguhan

**Comment by ajaniak** [comment]
`@unit="appendix"` is only in Canggu

**Comment by arlogriffiths** [comment]
Sorry, Axelle, EG p. 116 says:

> by default, `<citedRange>` will be understood to refer to page numbers, so references to pages can simply be added as the content of this element
> use a hyphen to record a range of pages, e.g. `<citedRange>12-21</citedRange>`
> the number of the last page should always be recorded in full, e.g. `<citedRange>123-124</citedRange>` (not 123-4 or 123-24)
> use a comma (followed by a space) to list non-adjacent pages, e.g. `<citedRange>12, 24</citedRange>`
> to refer to an entity other than a page, add the attribute `@unit` to `<citedRange>` with one of the following values

So I don't think at least the cases in Wurare.xml are encoding errors. 

Or do you think the EG shouild be changed on this point?

**Comment by ajaniak** [comment]
My mistake.

**Comment by arlogriffiths** [comment]
@ajaniak : can we close this issue now?
