### ISSUE TITLE
revision of Munduan.xml

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#25]
@ekobastiawan : Ihave just finished a first round of revising Munduan.xml.

You can see the differences between your first version and my revision here:

[https://github.com/erc-dharma/tfc-nusantara-epigraphy/commit/83903ddec72567280ac051ef08358baf76d06312](https://github.com/erc-dharma/tfc-nusantara-epigraphy/commit/83903ddec72567280ac051ef08358baf76d06312)

- Let me know if you have questions.
- Could you please look at the argr2ekba comments and take the necessary actions?
- Could you please add two more Weatherbee entries to Zotero, i.e. for the two items of which we now have pdfs in Sharedocs but for which we don't have Zotero entries yet?

Thanks!

**Comment by ekobastiawan** [comment]
@arlogriffiths : I have revised the initial encoding based on your suggestions, one more entry for Weatherbee (the PhD thesis) is still need to be added, the title of the thesis is not found in the pdf and I had difficulty finding it online. Could you tell me the title, please?

**Comment by arlogriffiths** [comment]
we need to add Moh. Oemar 1970 once we obtain a pdf of that publication
