### ISSUE TITLE
display of bibliography WuruTunggal.xml

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#27]
1. I am unable to get the "Primary" bibliography to appear in display: can you identify the source of the problem?
2. is it possible to modify the behavior of the structured bibliography so that text outside of `<ptr>` in `<bibl>` gets displayed? Example from this file:

`<bibl>Brandes in <ptr target="bib:NBG34_1896"/><citedRange unit="page">53</citedRange><citedRange unit="item">3</citedRange></bibl>`

3. Manu will discuss with you our requests for modifying display of bibliographic data in the case of short titles for journals. I guess some modification of our working method will be necessary to get a display like "Brandes in [ NBG 34 (1896)](url), 53 no. 3" for the above `<bibl>`.

**Comment by arlogriffiths** [comment]
Same problem re. "Primary" bibliography also in Guntur.xml.

With WuruduKidul.xml, it is the reverse: I only get "Primary" but not "Secondary" bibliography.

**Comment by ajaniak** [comment]
2. is possible now.

**Comment by arlogriffiths** [comment]
Thanks. Closing this issue. Moving point 3 to a new issue under project-documentation.
