### ISSUE TITLE
Version conflict on MpuManu.xml

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#28]
Dear all, 

MpuManu.xm has a version conflict. I am not sure whose in charge of this file, can someone handle it and clean the file to restore it to a stable state please? 
Thanks

**Comment by arlogriffiths** [comment]
I’ll take care of it a.s.a.p.


Le 3 nov. 2020 à 15:51, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



Dear all,

MpuManu.xm has a version conflict. I am not sure whose in charge of this file, can someone handle it and clean the file to restore it to a stable state please?
Thanks

**Comment by arlogriffiths** [comment]
I have resolved the conflicts.

I don't know who/what generated the derivative files _BACKUP, _BASE, _LOCAL, _REMOTE (see screenshot attached). 

@ajaniak : can you delete them now?


<img width="239" alt="Capture d’écran 2020-11-04 à 05 29 42" src="https://user-images.githubusercontent.com/835603/98069391-ebfe4200-1e5e-11eb-86cb-3243c1da54eb.png">

**Comment by ajaniak** [comment]
They are from a commit made by @ekobastiawan (2020-10-30). I can delete them of course.

**Comment by ajaniak** [comment]
I have moved them out the repository. I have kept a back-up version just in case. @ekobastiawan maybe you could also check the file to be sure all your work are still in it, if not let me know and I can fusion the content of the duplicated ones with the main. 
@arlogriffiths nothing was new when I pulled, can you push it please?

**Comment by arlogriffiths** [comment]
done. do you have the new file now?


Le 4 nov. 2020 à 10:09, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



I have moved them out the repository. I have kept a back-up version just in case. @ekobastiawan<https://github.com/ekobastiawan> maybe you could also check the file to be sure all your work are still in it, if not let me know and I can fusion the content of the duplicated ones with the main.
@arlogriffiths<https://github.com/arlogriffiths> nothing was new when I pulled, can you push it please?

**Comment by ajaniak** [comment]
Yes, thanks! the template has been updated for this file as well

**Comment by arlogriffiths** [comment]
good.

Eko wasn't aware himself of how those derived files ever got created, so I don't think they can contain anything of value. I think we can close this issue now
