### ISSUE TITLE
version conflit on Batutulis.xml

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#29]
Dear @aditiagunawan,

There is a conflict version on the Batutulis.xml file. Can you check it and keep the right part please? It starts with the line `<<<<<<< HEAD:provisional/aditiagunawan/Batutulis.xml` and ends at `>>>>>>> 1f1a1aa35461944634afd0ba248d6a64cb85f275:provisional/Java11Sundanese/Batutulis.xml` and is located inside the edition <div>. 

Let me know if you need help. 
Best,

**Comment by aditiagunawan** [comment]
Dear @ajaniak 
I resolved the conflict. So now we will have a new folder for these items? 

Best

**Comment by arlogriffiths** [comment]
Aditia: I don't know what you mean (and I think Axelle won't know either) but it seems you may not have done a git pull for a long time before you resumed working on the Sundanese inscriptions. Some months ago, I had introduced a new folder structure in tfc-nusantara-epigraphy/provisional, and you are expected to store your files in tfc-nusantara-epigraphy/provisional/Java11Sundanese.

In short, the structure is no longer based on encoder but on subgrouping of Nusantaran inscriptions.

Please never forget to do a git pull on any folder before you start working in it.

**Comment by ajaniak** [comment]
@aditiagunawan thank you for your work! it is indeed valide now.
