### ISSUE TITLE
folder structure

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#30]
please move the contents of  tfc-nusantara-epigraphy/provisional/aditiagunawan into the Sundanese folder, and then delete the aditiagunawan folder.

**Comment by aditiagunawan** [comment]
Dear @arlogriffiths 

I see all the files already move to Java11Sundanese. So It should simply delete it from my folder on the computer? How to delete the folder aditiagunawan? Thank you for your help.

**Comment by aditiagunawan** [comment]
Ok. Done.
