### ISSUE TITLE
Hampran

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#31]
Dear all, 

I order to make the workflow work on the tfc-nusantara, I am reworking/resolving files causing the failure. 
 
I have added fakes `<p>` for the section A and C, as well as encoded the `<l>` to complete the already encoded `<lg>` element for the part B of text for the file Hampran. Be careful when restarting the encoding; this structure might not match the content. 

@arlogriffiths you are the only one in the `<teiHeader>`, but I am not sure if it is really one of yours. 

Best,

**Comment by arlogriffiths** [comment]
Thanks. I had started encoding that inscription in May 2020 but never got far and then forgot about it. I have now finished encoding it and the file validates in Oxygen, but there is a problem in transformation:

<img width="1411" alt="Capture d’écran 2021-02-06 à 09 29 22" src="https://user-images.githubusercontent.com/835603/107113220-d6355a00-685d-11eb-8a3a-07eb0bc94918.png">

Can you determine the source of that problem, @ajaniak ?

**Comment by ajaniak** [comment]
There were a short title without tag and a wrong short title. I have corrected them and it should work now.

**Comment by arlogriffiths** [comment]
thanks a lot!
