### ISSUE TITLE
Missing Bosch1918_01

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#33]
Dear all, 

The Zotero Short Title `Bosch1918_01` is used in Canggu.xml and in Padingding.xml. But the data doesn't match any Zotero entry and I can't figure on my own which data is associated with it. Can you add the missing entry in Zotero or update the ZST  in the files to match an existing Zotero entry? 

Thanks

**Comment by arlogriffiths** [comment]
@m-schoettel : didn't you get this issue? 

**whenever you do receive an issue that concerns you, please make it a habit to take action soon and then close the issue!**

**Comment by m-schoettel** [comment]
I have now replaced the Zotero Short Title Bosch1918_01 in these two files with a `<bibl><ptr target="bib:OV1918"/></bibl>`, as this publication does not have a named author.
This issue is solved, closing it.
