### ISSUE TITLE
Workflow fail

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfc-nusantara-epigraphy#36]
Dear Axelle and Arlo,

May I ask you why every time I push a work in tfc, there will be a confirming email of workflow failure like this:

<img width="669" alt="Screenshot 2021-03-31 at 10 58 28" src="https://user-images.githubusercontent.com/55530631/113119108-5cdc3700-9210-11eb-8f4a-c6207decb86a.png">

Anyhow it seems that the file itself is updated in github.

Best,
Aditia

**Comment by ajaniak** [comment]
The XML files are always updated, the pipeline work once the files are done pushing on the shared repository. However, to run as expected it requires good quality data. For the last run, the DHARMA_INSIDENKSarvadharma.xml has been identified as not well-formed because of a version issue.

**Comment by arlogriffiths** [comment]
@aditiagunawan : I believe I recall Axelle has created a README page somewhere which explains more about this "pipeline", what it does for us and how it works.

@ajaniak : can you remind us where that README is? Also, I have just resolved the well-formedness problem of DHARMA_INSIDENKSarvadharma.xml and yet I still get a failure notice after my push.

**Comment by ajaniak** [comment]
An explanation of the pipeline have been given in the README of each repository

**Comment by arlogriffiths** [comment]
Thanks Axelle!
