### ISSUE TITLE
DHARMA_INSIDENKGarung - Zotero Short Title validation issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#37]
Dear @arlogriffiths and @ekobastiawan, 

There is an issue regarding the bib:Poerbatjaraka1920_01. It matches two entries in Zotero _Plaat te Soerakarta_ and _Transcripties van koperen platen_. Can you check and see if it can be resolved please? 

Best, 
Axelle

**Comment by arlogriffiths** [comment]
Thanks. I’ll take care of this one.

A


Le 9 avr. 2021 à 10:13, ajaniak ***@***.******@***.***>> a écrit :



Dear @arlogriffiths<https://github.com/arlogriffiths> and @ekobastiawan<https://github.com/ekobastiawan>,

There is an issue regarding the bib:Poerbatjaraka1920_01. It matches two entries in Zotero Plaat te Soerakarta and Transcripties van koperen platen. Can you check and see if it can be resolved please?

Best,
Axelle
