### ISSUE TITLE
DHARMA_INSIDENKWuruduKidul - missing lem in apparatus

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#40]
Dear @arlogriffiths, 

In your edition of Wurudu Kidul, it seems a `<lem>` is missing for the apparatus entry for 
```
<app loc="1v16">
	<rdg source="bib:Stutterheim1935_01 bib:Sarkar1971-1972_01 bib:Boechari1985-1986_01">makudur·</rdg>
	<rdg source="bib:Stutterheim1925_04">matudur·</rdg>
</app> 
```

Can you check it? let us know if this is a special case and a `<lem>`can't be provided so that we can update the Encoding Guide  if necessary. 

Best,

**Comment by arlogriffiths** [comment]
thanks! solved!
