### ISSUE TITLE
DHARMA_INSIDENKMula-Malurung - Several lem missing

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#43]
Dear @arlogriffiths  and @ekobastiawan, 

It seems several entries in your apparatus for the edition Mula-Malurung are missing their `<lem>`. Can you check it and see if it can be resolved according EGC rules? 

Thanks 
Best,

**Comment by arlogriffiths** [comment]
@ekobastiawan : please take care of this task too

**Comment by ekobastiawan** [comment]
Missing <lem>s have added to the apparatus

**Comment by ekobastiawan** [comment]
Missing <lem> have been added to the apparatus

**Comment by ekobastiawan** [comment]
Missing <lem> has been added to the apparatus
