### ISSUE TITLE
DHARMA_INSIDENKPadangRoco - attribute @n on an lg element

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#44]
Dear @ekobastiawan  and @arlogriffiths, 

In your edition Padang Roco, you have added a value `ABCD4` in an attribute `@n` for `<lg>`such as  `<lg n="ABCD4" met="anuṣṭubh">`. So far, we have planed to only have integer numbers as content for `@n` on `<lg>`.
Does it mean you need a broader offer of content for this attribute to encode this file? 

I see in the previous lines you have encoded similar content on `<lb/>` element such as `<lb n="ABCD4"/>`. Note that the value `ABCD4` appear twice in your file. Is it correct? 

Can you check this please? 

Thanks, 
Best,

**Comment by arlogriffiths** [comment]
I hadn’t yet had the change to revise Eko’s encoding.

Eko’s use of ABCD was one of the things I needed to think about but that seemed in need of correction. We’ll get to work on it asap.

Thanks!

Le 9 avr. 2021 à 10:58, ajaniak ***@***.******@***.***>> a écrit :



Dear @ekobastiawan<https://github.com/ekobastiawan> and @arlogriffiths<https://github.com/arlogriffiths>,

In your edition Padang Roco, you have added a value ABCD4 in an attribute @n for <lg>such as <lg n="ABCD4" met="anuṣṭubh">. So far, we have planed to only have integer numbers as content for @n on <lg>.
Does it mean you need a broader offer of content for this attribute to encode this file?

I see in the previous lines you have encoded similar content on <lb/> element such as <lb n="ABCD4"/>. Note that the value ABCD4 appear twice in your file. Is it correct?

Can you check this please?

Thanks,
Best,
