### ISSUE TITLE
DHARMA_INSIDENKRamesvarapura - Two Zotero Short Titles validation issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#45]
Dear @ekobastiawan, 

In your encoding of the edition Ramesvarapura, there are two Zotero Short Title that don't exist in Zotero Library: `bib:Pararaton`and `bib:Svacchandatantra`. Can you check this please? 
You seem to have use both to provide a reference using an empty `<ptr/>` element on its own. Let me know if you need help figuring out how to encode this or how to provide a reference for those two. 

Best,

**Comment by arlogriffiths** [comment]
Those are text titles and should be encoded with <title>, as prescribed in EGD.


Le 9 avr. 2021 à 11:04, ajaniak ***@***.******@***.***>> a écrit :



Dear @ekobastiawan<https://github.com/ekobastiawan>,

In your encoding of the edition Ramesvarapura, there are two Zotero Short Title that don't exist in Zotero Library: bib:Pararatonand bib:Svacchandatantra. Can you check this please?
You seem to have use both to provide a reference using an empty <ptr/> element on its own. Let me know if you need help figuring out how to encode this or how to provide a reference for those two.

Best,

**Comment by ekobastiawan** [comment]
Apparatus has been updated, closing this issue
