### ISSUE TITLE
DHARMA_INSIDENKBromoSemeru2 - Zotero Short Title issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#46]
Dear @m-schoettel and @arlogriffiths, 

In your edition Bromo Semeru 2,  Bromo Semeru 4 & Bromo Semeru 6, the Zotero Short title `SukartoAtmodjo1986_01`matches 4 entries in the Zotero Library: _Arti dan fungsi 'Pohon Hayat' dalam masyarakat Jawa Kuno_, _Menelusuri sejarah hari jadi Ngawi berdasarkan data prasasti kuno_, _Mengungkap masalah pembacaan Prasasti Pasrujambe_ and _The phallic symbol on the stone inscription of Samirana_. Can you check this and see if it can be resolved please? 

Thanks
Best,

**Comment by arlogriffiths** [comment]
I’ll take care of the necessary zotero operations and let Marine know when I have fixed the ZST to be cited for this inscription.




Le 9 avr. 2021 à 11:10, ajaniak ***@***.******@***.***>> a écrit :



Dear @m-schoettel<https://github.com/m-schoettel> and @arlogriffiths<https://github.com/arlogriffiths>,

In your edition Bromo Semeru 2, the Zotero Short title SukartoAtmodjo1986_01matches 4 entries in the Zotero Library: Arti dan fungsi 'Pohon Hayat' dalam masyarakat Jawa Kuno, Menelusuri sejarah hari jadi Ngawi berdasarkan data prasasti kuno, Mengungkap masalah pembacaan Prasasti Pasrujambe and The phallic symbol on the stone inscription of Samirana. Can you check this and see if it can be resolved please?

Thanks
Best,

**Comment by arlogriffiths** [comment]
@ajaniak : I have cleaned the zotero library and only one ZST SukartoAtmodjo1986_01 now remains, for the publication intended by Marine in the file in question. can you confirm that all is now in order and if so close this issue?

**Comment by ajaniak** [comment]
It seems fine for those files. Thanks
