### ISSUE TITLE
DHARMA_INSIDENKCanggu - Zotero Short Title validation issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#47]
Dear @m-schoettel, 

In your edition Canggu, you use the Zotero Short Title `SteinCallenfels_1918` but it doesn't match any Zotero entry. Can you check which entry it matches and updated it accordingly please? 

It also used in Kuśmala : `DHARMA_INSIDENKKusmala`.

Thanks

**Comment by m-schoettel** [comment]
Dear @ajaniak,

I have changed the ZST in these two files. Thanks!
