### ISSUE TITLE
DHARMA_INSIDENKKakalangan - Zotero Short Title validation Issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#48]
Dear @m-schoettel, 

In your edition Kakalangan, you have used the short title `vanNaerssen1941_01-1`. It can be found in Zotero Library. Since there is 2 entries for Naerssen in 1941, can you check this and updated to short title to match the right entry please? 

Thanks,

**Comment by m-schoettel** [comment]
Dear @ajaniak,

It is done! Thanks for spotting this.
