### ISSUE TITLE
DHARMA_INSIDENKNgadoman - Zotero Short Title Validation Issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#50]
Dear @arlogriffiths and @m-schoettel, 

In your edition Ngadoman, the zotero short title `CohenStuart1872_01` matches 3 entries: _Eerste vervolg catalogus der bibliotheek en catalogus der Maleische, Javaansche en Kawi handschriften van het Bataviaasch Genootschap van Kunsten en Wetenschappen_; _Inscriptie op een' steen in 's Rijks Museum van Oudheden te Leiden_ and _Inscriptie op een steen in 's Rijks Museum van Oudheden te Leiden_ (two of those being doublon ?). 
Note that this edition also use `CohenStuart1875_01`, see #38. 

Can you check this and update the Zotero Short Title accordingly please? 

thanks

**Comment by arlogriffiths** [comment]
I have disambiguated all the items CohenStuart1872 and CohenStuyart1875.

@ajaniak : could you check that the problem has disappeared and if so close this issue?
