### ISSUE TITLE
DHARMA_INSIDENKPabanyolan - Zotero Short Title Issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#51]
Dear @m-schoettel, 

In your edition Pabanyolan, you are using an old version of the Short title for NBG. Can you see to update it with the new pattern please? 

In this edition, you have also added an internal apparatus entry: 
```<app><note>Lime is one of the ingredients of a betel quid. See also OJED s.v. <foreign>apuh</foreign>, <foreign>apu</foreign>, kidung Vargasari 3.7b.</note></app>```
Unfortunately, it is not allowed for inscriptions like it is for manuscripts. Could you move it in the apparatus `<div>` if you want to keep this note please? 

Thanks

**Comment by m-schoettel** [comment]
Dear @ajaniak,

I have taken care of it, thanks. I have also moved the note to the apparatus division.
I seize the opportunity to ask you whether you understand why characters `&#x2028;` have been introduced in several places in this file (for instance, at the pb between recto and verso)?

**Comment by arlogriffiths** [comment]
@ajaniak 
I have seen strings like `&#x2028;` (I don't know if they were exactly the same) occur in other files as well, and in one case — a file I was working on with Salomé — have sinply removed such a string.

Maybe you could search all DHARMA files to see if such strings have surreptitiously crept in, and remove them all at once? Do you understand where they come from?

**Comment by ajaniak** [comment]
`&#x2028;` is the html code for the line separator. Oxygen must have converted them because they initially were not typed in a correct UTF-8 code and a forced conversion has been done to keep the file stable enough. 

I will clean them.
