### ISSUE TITLE
DHARMA_INSIDENKBatutulis - Zotero Short Title Validation Issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#52]
Dear @aditiagunawan,

In your edition Batu Tulis, you have issues with 2 Zotero Short Title:
- `Holle1869_01` matches 2 entries in Zotero Library: _De Batoe Toelis te Buitenzorg_ and _Bijdragen tot de geschiedenis der Preanger-Regentschappen_
- `Holle1882_01`matvhes 3 entries: _De Batoe-Toelis te Buitenzorg_, _Kawi Oorkonde_ and _Tabel van oud- en nieuw-Indische alphabetten: bijdrage tot de palaeographie van Nederlandsch-Indië_. 

Can you check this and see if it can be resolved please? 

Thanks

**Comment by aditiagunawan** [comment]
Dear @ajaniak 
I made a change in Zotero entries. Thank you. Done!

Adit

**Comment by ajaniak** [comment]
Thank you!
