### ISSUE TITLE
DHARMA_INSIDENKKawali_1a - Zotero Short Title Validation Issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-nusantara-epigraphy#53]
Dear @aditiagunawan, 

In your edition Kawali 1a , the Zotero Short title `Pleyte1911_03` doesn't exist. Can you check it and see if an entry must be added or if the short title have been change for the entry it was previously matching? 

Thanks

**Comment by aditiagunawan** [comment]
@ajaniak 
Thanks, Axelle. It is resolved. It should be `Pleyte1911_01`.

**Comment by ajaniak** [comment]
Great! Thank you for your help
