### ISSUE TITLE
remove small space from display of <pb>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#54]
@ajaniak -- Could you remove the small space which is inserted into display of `<pb>` before the avlue of @edRef?

<img width="183" alt="Capture d’écran 2021-05-20 à 13 53 03" src="https://user-images.githubusercontent.com/835603/118974270-e8ea1f80-b972-11eb-81a6-f7aac5ad8459.png">

Thanks!

**Comment by ajaniak** [comment]
Should be good now.
