### ISSUE TITLE
Update DHARMA_INSIDENKKaladi.xml error

### ISSUE THREAD

**Issue by wayanjarrah** [erc-dharma/tfc-nusantara-epigraphy#55]
Hi @ajaniak, I have been editing the Kaladi file and have pushed it, but it failed to update. I have checked in Atom and there are no linter errors – the file seems valid. Can you see where the problem is? Thanks

**Comment by ajaniak** [comment]
Hi @wayanjarrah, the issue was based on Short title in zotero rather than in the XML. It has been resolved and your edition is now displayed.

**Comment by wayanjarrah** [comment]
Thanks very much for that!

**Comment by wayanjarrah** [comment]
The same problem seems to have happened when I tried to update Taji. Is it the same zotero problem again, and is there something I can do at my end to prevent it from happening?

**Comment by ajaniak** [comment]
No sometimes it is just Zotero Api breaking down.

**Comment by wayanjarrah** [comment]
Ok!
