### ISSUE TITLE
pipeline jammed?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#59]
Dear @michaelnmmeyer !

Of the three last commits in this repo,. the last two seem not to have met with any validation problems. And yuet I don't see any new html being generated. Do you know why? Can you persuade the system to generate a new html?

Best,

Arlo

**Comment by wayanjarrah** [comment]
@arlogriffiths Your last push on Sarungga and mine on Panggumulan have gone through with new html generated, so it seems to be resolved.
