### ISSUE TITLE
ROD1923

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#64]
@wayanjarrah @ekobastiawan —

We currently have two zotero entries for ROD 1923, one with ZST "ROD1923", the other with ZST "ROD1923_01". 

I prefer the contents of the latter but the ZST of the former is more consistent with the ZSTs for the other ROD volumes.

Before I make the merge, please check the spreadsheets for IDENK batches 2 and 3 to make sure any occurrences of ROD1923_01 are changed to ROD1923.

Let me know when you're done by answering this issue.

I have searched in our xml files and I believe neither of the two ZSTs is ever cited.

**Comment by ekobastiawan** [comment]
I have checked both spreadsheets and make necessary adjustment
