### ISSUE TITLE
parujar and pakaraṇān translations

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#66]
@ekobastiawan  —

please search in our xml files in tfc-nusantra-epigraphy all occurrences of 

1. "spokesman", "spokesmen" and possibly "spokesperson(s)" 
2. "court" (when used as translation of pakaraṇān)

please change 1 to "herald(s)" and 2 to "secretariat"

(cc to @wayanjarrah for his information)

**Comment by ekobastiawan** [comment]
I have made the necessary adjustments but let me know If there are any files that I missed

**Comment by arlogriffiths** [comment]
thanks. 
you didn't find any cases in Sangguran and Wurudu Kidul? 
did you use the function "search in files" in Oxygen? see screenshot.

<img width="1036" alt="Capture d’écran 2024-04-01 à 14 00 04" src="https://github.com/erc-dharma/tfc-nusantara-epigraphy/assets/835603/5dc78a53-4029-4347-bc72-8723db5f9fd9">

**Comment by ekobastiawan** [comment]
I have checked (with the help of Bli Jarrah) all cases of "spokesman", "spokesmen" and "spokesperson(s)" and replaced them with herald(s), as well as replacing "court" (pakaraṇān) to "secretariat"

**Comment by arlogriffiths** [comment]
thanks a lot.
