### ISSUE TITLE
how to cite Damais 1952 and 1955

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-nusantara-epigraphy#9]
In the sec. bibl. sections of your bibliographies, please try always to capture all the bibliographically relevant details, not only the pages. Thus, for publications of the nature of an inventory, or relying on inventiry numbers, such as Damais 1952 and 1955, I recommend the following format (from my work in progress on encoding Wurare)

`<bibl><ptr target="bib:Damais1952_01"/><citedRange unit="page">72-73</citedRange><citedRange unit="item">A.174</citedRange></bibl>
<bibl><ptr target="bib:Damais1955_01"/><citedRange unit="page">79</citedRange><citedRange unit="item">A.174</citedRange></bibl>
`

please revise your `<bib>`s on this point, and respond to this issue with "I'm done" when you're done.

**Comment by ekobastiawan** [comment]
I'm done

**Comment by arlogriffiths** [comment]
@ekobastiawan , @m-schoettel : this is a reminder for you two.

**Comment by arlogriffiths** [comment]
@aditiagunawan , @m-schoettel : this is a reminder for you two (although I don't know if Aditia has encoded any inscriptions where my instruction is relevant)

**Comment by m-schoettel** [comment]
It's done too.

**Comment by arlogriffiths** [comment]
@aditiagunawan : we're waiting for you on this one (though maybe your files never need to cite Damais, Nakada, or any such inventory). Just let us know.

**Comment by aditiagunawan** [comment]
Until now I not found yet such cases, but I will keep in mind and save this notice. Probably one day I use it when dealing with the manuscript metadata.

**Comment by arlogriffiths** [comment]
OK, so I'm closing this issue now.
